apiVersion: v1
kind: Service
metadata:
  name: python
spec:
  selector:
    app: python
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
spec:
  selector:
    matchLabels:
      app: python
  replicas: 4
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: us.gcr.io/devops-307515/python:$Image
        imagePullPolicy: Always
      imagePullSecrets:
      - name: gcr-json-key 
        ports:
        - containerPort: 5000