apiVersion: v1
kind: Service
metadata:
  name: nodejs
spec:
  selector:
    app: nodejs
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  selector:
    matchLabels:
      app: nodejs
  replicas: 4
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: python
        image: us.gcr.io/devops-307515/nodejs:$Image
        imagePullPolicy: Always
      imagePullSecrets:
      - name: gcr-json-key 
        ports:
        - containerPort: 8080