apiVersion: v1
kind: Service
metadata:
  name: springboot
spec:
  selector:
    app: springboot
  ports:
  - protocol: "TCP"
    port: 18999
    targetPort: 18999
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
spec:
  selector:
    matchLabels:
      app: springboot
  replicas: 4
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        image: $springbootimagePath
        imagePullPolicy: Always
      imagePullSecrets:
      - name: gcr-json-key 
        ports:
        - containerPort: 18999